#!/bin/sh

# Get CSV of youtube subscriptions from https://takeout.google.com/
## Click "Deselect all", then select only Youtube at the very bottom of the list, click "All data included" right below Youtube field and select only subscriptions, then do single export and place the CSV file in the same folder as this script, names "Abos.csv"

file="Abos.csv"

read -p "Enter your full YouTube RSS URL (e.g. ftrss.johnsmith.com): " FTRSS_URL

leftend="https://$FTRSS_URL/makefulltextfeed.php?url=sec%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fchannel_id%3D"
rightend="&max=15&links=preserve&exc=&submit=Create+Feed"

while IFS=$',' read -r channel_id channel_url channel_title; do
    echo "$leftend$channel_id$rightend" >> feedlinks
done < "$file"